name: masl
volumes:
  conan-cache:
    name: conan-cache

services:
  masl-dev:
    image: levistarrett/masl-dev:${MASL_VERSION:-latest}
    build:
      context: masl-dev
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
    profiles:
      - tools
      - all
