name: Build Docker
on: workflow_dispatch
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push base
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile.masl-base
          platforms: linux/arm64,linux/amd64
          push: true
          tags: levistarrett/masl-base:latest
      - name: Build and push build
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile.masl-build
          platforms: linux/arm64,linux/amd64
          push: true
          tags: levistarrett/masl-build:latest
      - name: Build and push compiler
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile.masl-compiler
          platforms: linux/arm64,linux/amd64
          push: true
          tags: levistarrett/masl-compiler:latest
      - name: Build and push exe
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile.masl-exe
          platforms: linux/arm64,linux/amd64
          push: true
          tags: levistarrett/masl-exe:latest
